CREATE TABLE weather_raw (
    ID        SERIAL PRIMARY KEY,
    CD_ESTACAO VARCHAR(10) NOT NULL,
    DATATIME TIMESTAMP NOT NULL,
    TEMP_INST FLOAT,
    TEMP_MAX FLOAT,
    TEMP_MIN FLOAT,
    UMD_INST FLOAT,
    PR_INST FLOAT,
    VEN_VEL FLOAT,
    CHUVA FLOAT,
    INSERTED_AT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE weather_daily_summary (
    DATA DATE,
    CD_ESTACAO VARCHAR(10) NOT NULL,
    TEMPERATURA_ISNT FLOAT,
    TEMPERATURA_MAX FLOAT,
    TEMPERATURA_MIN FLOAT,
    UMDIDADE_INST FLOAT,
    PRESSAO_INST FLOAT,
    VENTO_VEL FLOAT,
    CHUVA FLOAT,
    PRIMARY KEY (DATA, CD_ESTACAO)
);